@startuml
    class TestFixture
    note bottom: Singleton Object\ndoes all the required\nsetup for the test\ncreates Frontend, Backend and\nFetchDataService \n
    
    class FetchDataService
        FetchDataService : -backend
    note top: FetchDataService uses Backend\nto call required WebService call
    class Frontend
    class Backend
    
    
    class BasePage
    class HomePage
    class RegistrationPage
    
    class TestBase
        TestBase : -frontend
        TestBase : -fetchdata_service
    class TestHomePage
    class TestRegistrationPage
    
    
    BasePage <|-- HomePage
    BasePage <|-- RegistrationPage
    TestBase <|-- TestHomePage
    TestBase <|-- TestRegistrationPage
    
    TestBase ..> TestFixture
    
    TestHomePage ..> HomePage
    TestRegistrationPage ..> RegistrationPage
@enduml
